var courselist = [
  { "xqj": 1, "sksj": 1, "skcd": 2, "kcxx": "Breaking入门   教室A   4-8月" },
  { "xqj": 1, "sksj": 3, "skcd": 2, "kcxx": "" },
  { "xqj": 1, "sksj": 6, "skcd": 2, "kcxx": "" },
  { "xqj": 1, "sksj": 8, "skcd": 2, "kcxx": "Hiphop基础   教室B   8-10月" },
  { "xqj": 1, "sksj": 10, "skcd": 2, "kcxx": "" },
  { "xqj": 1, "sksj": 12, "skcd": 2, "kcxx": "" },
  { "xqj": 2, "sksj": 1, "skcd": 2, "kcxx": "" },
  { "xqj": 2, "sksj": 3, "skcd": 2, "kcxx": "Breaking入门   教室C   4-8月" },
  { "xqj": 2, "sksj": 6, "skcd": 2, "kcxx": "通用律动   教室B   5-10月" },
  { "xqj": 2, "sksj": 8, "skcd": 2, "kcxx": "" },
  { "xqj": 2, "sksj": 10, "skcd": 2, "kcxx": "" },
  { "xqj": 2, "sksj": 12, "skcd": 2, "kcxx": "" },
  { "xqj": 3, "sksj": 1, "skcd": 2, "kcxx": "" },
  { "xqj": 3, "sksj": 3, "skcd": 2, "kcxx": "Breaking私教课   教室A   4-5月" },
  { "xqj": 3, "sksj": 6, "skcd": 2, "kcxx": "Hiphop基础   教室B   8-10月" },
  { "xqj": 3, "sksj": 8, "skcd": 2, "kcxx": "" },
  { "xqj": 3, "sksj": 10, "skcd": 2, "kcxx": "" },
  { "xqj": 3, "sksj": 12, "skcd": 2, "kcxx": "" },
  { "xqj": 4, "sksj": 1, "skcd": 2, "kcxx": "通用律动   教室B   5-10月" },
  { "xqj": 4, "sksj": 3, "skcd": 2, "kcxx": "" },
  { "xqj": 4, "sksj": 6, "skcd": 2, "kcxx": "Poppin提高   教室A   4-8月" },
  { "xqj": 4, "sksj": 8, "skcd": 2, "kcxx": "Breaking私教课   教室A   4-5月" },
  { "xqj": 4, "sksj": 10, "skcd": 2, "kcxx": "舞种选修   教室C   6-10月" },
  { "xqj": 4, "sksj": 12, "skcd": 2, "kcxx": "" },
  { "xqj": 5, "sksj": 1, "skcd": 2, "kcxx": "" },
  { "xqj": 5, "sksj": 3, "skcd": 2, "kcxx": "Poppin提高   教室A   4-8月" },
  { "xqj": 5, "sksj": 6, "skcd": 2, "kcxx": "" },
  { "xqj": 5, "sksj": 8, "skcd": 2, "kcxx": "" },
  { "xqj": 5, "sksj": 10, "skcd": 2, "kcxx": "" },
  { "xqj": 5, "sksj": 12, "skcd": 2, "kcxx": "" },
  { "xqj": 6, "sksj": 1, "skcd": 2, "kcxx": "" },
  { "xqj": 6, "sksj": 3, "skcd": 2, "kcxx": "" },
  { "xqj": 6, "sksj": 6, "skcd": 2, "kcxx": "" },
  { "xqj": 6, "sksj": 8, "skcd": 2, "kcxx": "" },
  { "xqj": 6, "sksj": 10, "skcd": 2, "kcxx": "" },
  { "xqj": 6, "sksj": 12, "skcd": 2, "kcxx": " " },
  { "xqj": 7, "sksj": 1, "skcd": 2, "kcxx": " " },
  { "xqj": 7, "sksj": 3, "skcd": 2, "kcxx": " " },
  { "xqj": 7, "sksj": 6, "skcd": 2, "kcxx": " " },
  { "xqj": 7, "sksj": 8, "skcd": 2, "kcxx": "  " },
  { "xqj": 7, "sksj": 10, "skcd": 2, "kcxx": "" },
  { "xqj": 7, "sksj": 12, "skcd": 2, "kcxx": " " }
];
//模块化
module.exports = {
  courselist: courselist
}
